/* ============================================================
   PHOTO LIST  —  GENERATED by build-photos.py. Do not add photos
   by hand here; drop image files in photos/ and re-run:

       py build-photos.py

   You MAY edit the caption text below — your edits are preserved
   on the next rebuild (matched by the orig filename).
   ============================================================ */

window.PHOTOS = [
  { thumb: "photos/thumbs/AbbyCod032793-R1-022 3.jpg", view: "photos/view/AbbyCod032793-R1-022 3.jpg", orig: "photos/AbbyCod032793-R1-022 3.JPG", caption: "Untitled no. 1", w: 1070, h: 1600 },
  { thumb: "photos/thumbs/AbbyCod032793-R1-026 2.jpg", view: "photos/view/AbbyCod032793-R1-026 2.jpg", orig: "photos/AbbyCod032793-R1-026 2.JPG", caption: "Untitled no. 2", w: 1600, h: 1070 },
  { thumb: "photos/thumbs/AbbyCod_AbbyCod-R1-E030.jpg", view: "photos/view/AbbyCod_AbbyCod-R1-E030.jpg", orig: "photos/AbbyCod_AbbyCod-R1-E030.JPG", caption: "Untitled no. 3", w: 1600, h: 1070 },
  { thumb: "photos/thumbs/AbbyCod_AbbyCod-R2-018-7A 3.jpg", view: "photos/view/AbbyCod_AbbyCod-R2-018-7A 3.jpg", orig: "photos/AbbyCod_AbbyCod-R2-018-7A 3.JPG", caption: "Untitled no. 4", w: 1070, h: 1600 },
];

/* ============================================================
   PRINT SIZES  —  edit dimensions / prices here (preserved on rebuild).
   Set price to "" (empty) to hide the price line.
   ============================================================ */

window.PRINT_SIZES = [
  { dim: "4 × 6", price: "" },
  { dim: "5 × 7", price: "" },
  { dim: "8 × 10", price: "" },
  { dim: "11 × 14", price: "" },
];
